version: '3'
services:
  backendend:
    build: ./backend
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 1GB
        reservations:
          memory: 512M
    #network_mode: host

  frontendend:
    build: ./frontend
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 1GB
        reservations:
          memory: 512M
    #network_mode: host
